Repository googleapis/sloth, pull requests merged in 2019-05, with the labels that each got.

#214 Add gaxios lib
  repos.json
  users.json
Labels: cla: yes

#215 add 3 new Node.js repos to sloth
  repos.json
  users.json
Labels: cla: yes

#217 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#216 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#219 Add cloud-cpp team to google-cloud-cpp-spanner.
  repos.json
  users.json
Labels: cla: yes

#220 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#221 chore: release 4.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#224 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#226 add ruby-style to repos.json
  repos.json
Labels: cla: yes

#225 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#223 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#222 build: update build scripts
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#228 refactor: use drift API to get repo issues
  package.json
  src/issue.ts
  src/slo.ts
  src/types.ts
  test/fixtures/driftResponse.json
Labels: cla: yes

#229 fix: use the drift prod enpoint
  src/issue.ts
Labels: cla: yes

#230 fix: remove suprious log
  src/issue.ts
Labels: cla: yes

#233 fix: check for unknown priority
  src/issue.ts
  src/types.ts
Labels: cla: yes

#235 chore: update github userID
  users.json
Labels: cla: yes

#236 fix: use issue_number for tag issues
  package.json
  src/issue.ts
Labels: cla: yes

#234 build: update kokoro build config
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#237 chore: release 4.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#238 feat: add phishing protection
  repos.json
Labels: cla: yes

#239 chore: release 4.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#241 build: add configuration for automated doc deployemnt
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#243 chore: add grafeas to list of repos
  repos.json
Labels: cla: yes

#245 feat: remove labels we do not want
  src/label.ts
Labels: cla: yes

#248 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#244 fix: bump minimim version
  package.json
Labels: cla: yes

#247 build: add DRIFT key to kokoro job
  .kokoro/release/tag-issues.cfg
  .kokoro/tag-issues.sh
Labels: cla: yes

#249 chore: release 4.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#251 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#250 Add nnegrey to yoshi-python.
  users.json
Labels: cla: yes

#253 fix: check for assignees
  src/issue.ts
Labels: cla: yes

#254 add hongalex@ as a Go developer (working on pubsub)
  users.json
Labels: cla: yes
