Repository googleapis/sloth, pull requests merged in 2019-03, with the labels that each got.

#179 Add docuploader repository.
  repos.json
Labels: cla: yes

#180 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#178 build: update release config
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes

#181 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#182 Moving cloud-bigtable-client to googleapis
  repos.json
  users.json
Labels: cla: yes

#184 Fix users.json
  users.json
Labels: cla: yes

#185 Adding olavloite to the java team
  users.json
Labels: cla: yes

#186 chore: remove GoogleCloudPlatform org
  repos.json
  src/repos.ts
  users.json
Labels: cla: yes

#187 chore: add bcoe to python, ruby, cpp, nodejs
  users.json
Labels: cla: yes

#188 Add googleapis/google-auth-library-python-oauthlib to repos
  repos.json
  users.json
Labels: cla: yes

#190 Added andrei-semeniuk to yoshi team
  users.json
Labels: cla: yes

#189 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#192 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#194 add Emmanuel to Go
  users.json
Labels: cla: yes

#196 Add andreamlin to yoshi-java
  users.json
Labels: cla: yes

#197 Add Peter Lamut to yoshi-python
  users.json
Labels: cla: yes

#199 Adding Seth and Tim
  users.json
Labels: cla: yes

#200 Add alixhami to python
  users.json
Labels: cla: yes

#202 Release @justinbeckwith/sloth v3.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: automerge, autorelease: pending, cla: yes
