Repository googleapis/sloth, pull requests merged in 2020-07, with the labels that each got.

#735 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#736 fix: add BigQuery Reservation
  repos.json
Labels: cla: yes

#738 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#740 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#741 fix: add ability to set language via label
  src/issue.ts
Labels: cla: yes

#743 chore: add proto-plus-python to repo list
  repos.json
Labels: cla: yes

#744 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#745 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#747 chore: add python-functions and python-analytics-admin
  repos.json
Labels: cla: yes

#746 build: rename _toc to toc, add config files for cloud-rad, add missing closing paren in publish script
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: full

#749 fix: add jsdoc-region-tag repository
  repos.json
Labels: cla: yes

#751 chore: add Java analytics-admin, functions, notebooks repos
  repos.json
Labels: cla: yes

#752 feat: add nodejs-analytics-admin and nodejs-functions
  repos.json
Labels: cla: yes

#755 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#753 feat: add doc repos and teams
  repos.json
  teams.json
Labels: cla: yes

#756 chore: add proto-plus-python to actools
  teams.json
Labels: cla: yes

#758 chore: rename java-gameservices to java-game-servers
  repos.json
Labels: cla: yes

#759 fix: makes proto-plus-python issues team managed
  repos.json
Labels: cla: yes

#761 fix: add python-audit-log to repos
  repos.json
Labels: cla: yes

#760 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
