Repository googleapis/sloth, pull requests merged in 2020-08, with the labels that each got.

#766 chore: add python-notebooks
  repos.json
  teams.json
Labels: cla: yes

#765 chore: allow code-suggester releases
  repos.json
Labels: automerge, cla: yes

#767 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#770 chore: attribute documentai to cloud-ai team
  teams.json
Labels: cla: yes

#771 build: perform publish using Node 12, chore: update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes, context: full

#769 fix: updating list of APIs owned by code-build-run team
  teams.json
Labels: cla: yes

#774 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#777 chore: add python dialogflow-cx and transcoder repos
  repos.json
Labels: cla: yes

#779 feat(node): add dialogflow-cx
  repos.json
Labels: cla: yes

#782 fix: update teams.json to fix ownership of "notebooks" API
  teams.json
Labels: cla: yes

#784 build: nightly flake tracking; fix releasetool perms
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
Labels: cla: yes

#785 fix: drop java-bigtable-emulator from repos
  repos.json
Labels: cla: yes
