Repository googleapis/sloth, pull requests merged in 2020-04, with the labels that each got.

#619 build: set AUTOSYNTH_MULTIPLE_COMMITS=true for context aware commits
  synth.py
Labels: automerge, cla: yes

#618 fix: add python-spanner-django repo
  repos.json
Labels: automerge, cla: yes

#621 feat: add nodejs-memcache
  repos.json
Labels: cla: yes

#622 feat: add java-accesscontextmanager, java-os-config
  repos.json
Labels: cla: yes

#620 chore: update eslint and prettier configs
  .eslintrc.json
  .prettierignore
  .prettierrc.js
  synth.metadata
Labels: automerge, cla: yes

#623 chore: remove duplicate mocha config
  .mocharc.json
Labels: automerge, cla: yes

#573 feat: Use field_mask for faster retrieval of issues
  src/issue.ts
Labels: automerge, cla: yes

#626 fix: apache license URL (#468)
  .prettierrc.js
  synth.metadata
Labels: cla: yes

#628 build: remove unused codecov config
  codecov.yaml
Labels: automerge, cla: yes

#627 feat: add bradmiro to java and python
  users.json
Labels: automerge, cla: yes

#578 feat: add suraj-qlogic to yoshi-java team
  users.json
Labels: cla: yes

#629 chore: update lint ignore files
  .eslintignore
  .prettierignore
Labels: automerge, cla: yes

#631 fix: remove the google-cloud-cpp-bigquery repo
  repos.json
Labels: cla: yes

#632 fix: remove field mask due to closed issues being returned
  src/issue.ts
Labels: cla: yes

#638 fix: re-enable the field mask
  src/issue.ts
Labels: cla: yes

#635 build: use codecov's action, now that it's authless
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes

#639 feat: add python-recaptcha-enterprise
  repos.json
  users.json
Labels: cla: yes

#641 feat: add python-api-common-protos
  repos.json
  users.json
Labels: cla: yes

#643 fix: remove the google-cloud-cpp-pubsub repo
  repos.json
Labels: automerge, cla: yes

#645 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes

#647 fix: add nodejs-local-auth
  repos.json
  users.json
Labels: cla: yes

#648 feat: add python-test-utils
  repos.json
  users.json
Labels: automerge, cla: yes

#650 cleanup: remove google-cloud-cpp-common
  repos.json
Labels: automerge, cla: yes

#649 feat: add BigQuery Connections, BigQuery Reservations repos.
  repos.json
  users.json
Labels: automerge, cla: yes, kokoro:force-run

#654 fix: add storagetransfer API to SoDa team
  teams.json
Labels: automerge, cla: yes

#658 chore: update BQ new repo names
  repos.json
  users.json
Labels: cla: yes

#659 chore: remove sync-repo-settings
  required-checks.json
  src/cli.ts
  src/repos.ts
Labels: cla: yes
