Repository googleapis/sloth, pull requests merged in 2020-09, with the labels that each got.

#787 fix: add nodejs-analytics-data library
  repos.json
Labels: cla: yes

#789 fix: catch-all samples issues go to onramp
  src/issue.ts
Labels: cla: yes

#791 feat(repos): adds nodejs-notebooks repo
  repos.json
Labels: automerge, cla: yes

#793 feat: add retry logic with backoff
  src/issue.ts
Labels: cla: yes

#796 build: update to latest publish and test config
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, context: none

#798 chore: add python-analytics-data and python-area120-tables
  repos.json
Labels: cla: yes

#801 feat: add Node.js libraries area-120-tables, assured-workloads, workflows
  repos.json
Labels: cla: yes

#804 feat(repos): adds nodejs-ai-platform repo
  repos.json
Labels: cla: yes

#803 chore: add nodejs-security-private-ca to repos.json
  repos.json
Labels: cla: yes
