Repository googleapis/sloth, pull requests merged in 2020-05, with the labels that each got.

#660 chore: unpin version of gts
  package.json
Labels: automerge, cla: yes

#661 feat(java): add java-common-protos repo
  repos.json
Labels: cla: yes

#663 chore: add python-bigquery-reservation
  repos.json
  users.json
Labels: cla: yes

#665 feat(java): add java-iam repo
  repos.json
Labels: cla: yes

#669 feat: add python orgpolicy and accesscontextmanager
  repos.json
  users.json
Labels: cla: yes

#671 feat: add os-config
  repos.json
  users.json
Labels: cla: yes

#670 fix(deps): upgrade to meow 7.x
  package.json
Labels: automerge, cla: yes

#676 feat: adding missing repos and update teams
  repos.json
  teams.json
Labels: cla: yes

#674 fix: adds intern to python
  users.json
Labels: automerge, cla: yes

#679 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#684 fix: add java-pubsublite repository
  repos.json
Labels: cla: yes

#685 feat: add python-bigquery-connection repo
  repos.json
  users.json
Labels: cla: yes

#687 fix: add jsdoc-fresh repos
  repos.json
Labels: automerge, cla: yes

#688 fix: remove bcoe from teams they're not contributing to
  users.json
Labels: cla: yes

#689 clean: remove the 'cpp-cmakefiles' repo
  repos.json
Labels: cla: yes

#690 chore: moves ndb to soda team
  teams.json
Labels: cla: yes

#692 fix: assign more APIs to cake
  teams.json
Labels: cla: yes
