Repository googleapis/sloth, pull requests merged in 2020-10, with the labels that each got.

#809 chore(python): add workflows, private ca, assured workloads
  repos.json
Labels: cla: yes

#797 build!: update build configuration enable engines strict
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .mocharc.js
  package.json
  synth.metadata
  synth.py
Labels: api: cloudbuild, cla: yes, context: partial

#813 fix(build): switch to trampoline 2 (release as patch rather than major)
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: cla: yes

#818 chore: update teams.json
  teams.json
Labels: cla: yes

#820 fix: remove trailing comma
  teams.json
Labels: automerge, cla: yes

#822 build: deploy to cloud run for crons
  .gitignore
  Dockerfile
  package-lock.json
  package.json
  src/exportToSheets.ts
  src/server.ts
Labels: cla: yes

#823 chore(deps): update package-lock.json
  samples/package-lock.json
  synth.metadata
Labels: cla: yes, context: none

#824 chore: stop tracking package-lock.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#825 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#828 deps: update gaxios in samples
  samples/package-lock.json
  synth.metadata
Labels: cla: yes, context: none

#830 build: changes to package-lock.json
  samples/package-lock.json
  synth.metadata
Labels: cla: yes, context: none

#833 docs: updated code of conduct
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  samples/package-lock.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#834 build: update to the latest build config
  samples/package-lock.json
  synth.metadata
Labels: cla: yes, context: none

#838 feat(node): add nodejs-video-transcoder
  repos.json
Labels: cla: yes
