Repository googleapis/sloth, pull requests merged in 2020-06, with the labels that each got.

#694 chore: remove google-cloud-cpp-spanner
  repos.json
Labels: cla: yes

#695 fix: add meredithslota to teams they triage/assign
  users.json
Labels: automerge, cla: yes

#701 feat: add xiaozhenliu to yoshi-python
  users.json
Labels: cla: yes

#704 fix: add python-os-config repo
  repos.json
  users.json
Labels: cla: yes

#703 fix: add APIs to AnIML teams
  teams.json
Labels: automerge, cla: yes

#708 fix: Adding stackdriver-sandbox and cloud-code-samples
  repos.json
Labels: cla: yes

#711 fix: corrects shortname for Cloud Translation API
  teams.json
Labels: automerge, cla: yes

#705 feat(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#715 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: cla: yes, context: full

#716 refactor: drop dependency on octokit
  package.json
  src/issue.ts
  src/users.ts
  src/util.ts
Labels: cla: yes

#717 fix: update APM team attribution
  teams.json
Labels: cla: yes

#719 fix: include new CAKE repos in teams
  teams.json
Labels: cla: yes

#720 chore: remove noahdietz from yoshi-php
  users.json
Labels: cla: yes

#722 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#725 chore: add intern yangnuoyu to yoshi-java
  users.json
Labels: cla: yes

#726 chore: add nodejs-bigquery-connection
  repos.json
Labels: cla: yes

#729 chore: remove the users and team sync feature
  README.md
  package.json
  src/cli.ts
  src/types.ts
  src/users.ts
  src/util.ts
  test/verifyConfigs.test.ts
  users.json
Labels: cla: yes

#731 feat: data-analytics is its own team
  teams.json
Labels: cla: yes

#733 chore: remove python-irm from repo list
  repos.json
Labels: automerge, cla: yes

#734 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full
