Repository googleapis/sloth, pull requests merged in 2021-01, with the labels that each got.

#865 feat(python): add python-compute and python-binary-authorization
  repos.json
Labels: cla: yes

#866 feat(python): add python-channel and python-retail
  repos.json
Labels: cla: yes

#868 feat(python): add python-network-connectivity and python-domains
  repos.json
Labels: cla: yes

#869 fix: add aiplatform api
  teams.json
Labels: cla: yes

#864 build: update build config and contrib guide
  .kokoro/trampoline_v2.sh
  CONTRIBUTING.md
  samples/package-lock.json
  synth.metadata
Labels: cla: yes, context: partial

#871 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  samples/package-lock.json
  synth.metadata
Labels: cla: yes, context: partial

#873 feat: scan entire googleapis org
  Dockerfile
  package.json
  repos.json
  src/issue.ts
  src/repos.json
  src/slo.ts
  src/teams.json
  src/types.ts
  src/util.ts
  test/verifyConfigs.test.ts
  tsconfig.json
Labels: cla: yes

#874 chore: add eventarc and workflows APIs to serverless team
  src/teams.json
Labels: automerge, cla: yes
