Repository googleapis/sloth, pull requests merged in 2021-06, with the labels that each got.

#886 chore: add mediatranslation api
  src/teams.json
Labels: automerge, cla: yes

#940 chore: add runtimeconfig to Cloud/GCP denylist
  src/services.json
Labels: automerge, cla: yes

#942 chore: adds bigtabletableadmin to Cloud/GCP denylist
  src/services.json
Labels: cla: yes

#943 chore: adds run, sourcerepo to Cloud/GCP deny list
  src/services.json
Labels: cla: yes

#936 fix: use the service management module
  package-lock.json
  package.json
  src/fetchServices.ts
Labels: cla: yes

#949 chore: add ondemandscanning to Cloud/GCP denylist
  src/services.json
Labels: cla: yes

#954 chore: break out anthos/gke api and repos
  src/teams.json
Labels: cla: yes

#955 refactor: use split apiary module
  package-lock.json
  package.json
  src/exportToSheets.ts
  src/fetchServices.ts
  test/test.exportToSheets.ts
Labels: cla: yes

#956 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: automerge, cla: yes

#958 chore: adds meshca to Cloud/GCP denylist
  src/services.json
Labels: cla: yes

#959 fix: samples to yoshi
  package-lock.json
  src/repos.json
  src/teams.json
Labels: cla: yes, samples

#962 chore: adds sqladmin, opsconfigmonitoring to Cloud/GCP deny list
  src/services.json
Labels: cla: yes

#961 fix: remove onramp specific assignment for samples
  src/issue.ts
Labels: cla: yes, samples

#963 feat: add sphinx-docfx-yaml repo under CXE team
  src/teams.json
Labels: cla: yes
