Repository googleapis/sloth, pull requests merged in 2021-05, with the labels that each got.

#888 feat: adds inScope classification and other details
  package-lock.json
  package.json
  src/cli.ts
  src/fetchServices.ts
  src/services.json
  test/fixtures/serviceConfigList.json
  test/test.fetchServices.ts
Labels: cla: yes

#925 chore: adds recommendationengine to services deny list
  src/services.json
Labels: cla: yes

#927 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/generated-files-bot.yml
  owlbot.py
  synth.metadata
  synth.py
Labels: cla: yes

#926 build: populate ignoreAuthors for generated-files-bot
  package-lock.json
  src/cli.ts
  src/exportToBigQuery.ts
  src/slo.ts
Labels: cla: yes, context: partial

#929 chore: adds services to Cloud/GCP denylist
  src/services.json
Labels: cla: yes

#932 chore: adds ml to Cloud/GCP deny list
  src/services.json
Labels: automerge, cla: yes

#934 fix!: remove policy tools
  src/cli.ts
  src/policy.ts
  src/server.ts
  test/test.policy.ts
Labels: cla: yes

#937 chore: add baremetalsolutions to denylist
  src/services.json
Labels: cla: yes

#938 fix: correct spelling of baremetalsolution
  src/services.json
Labels: automerge, cla: yes
