Repository googleapis/sloth, pull requests merged in 2021-02, with the labels that each got.

#876 feat: add policy tracking
  package-lock.json
  package.json
  src/cli.ts
  src/policy.ts
  src/server.ts
  src/types.ts
Labels: cla: yes

#875 chore: update lock file
  samples/package-lock.json
  synth.metadata
Labels: cla: yes, context: none

#878 chore: update package-lock.json
  samples/package-lock.json
  synth.metadata
Labels: cla: yes, context: none

#879 fix: renovate.json can be in the .github directory
  src/policy.ts
Labels: automerge, cla: yes

#880 fix: use GitHub API to fetch code of conduct
  src/policy.ts
  src/types.ts
  src/util.ts
Labels: cla: yes

#882 fix: do not use preview CoC API
  src/policy.ts
  src/util.ts
Labels: cla: yes

#881 fix: separate databases team into infra and cloud native
  src/teams.json
Labels: cla: yes

#877 feat: update SoDa repos
  src/repos.json
  src/teams.json
Labels: cla: yes

#883 feat: new c++ repository
  src/repos.json
Labels: cla: yes

#885 fix: include cpp functions framework for cxx team
  src/teams.json
Labels: cla: yes

#884 feat: adds export of Cloud API classification
  .gitignore
  package-lock.json
  src/fetchServices.ts
  src/server.ts
  src/types.ts
Labels: cla: yes

#887 feat: adds usage/ToS to Cloud APIs export
  src/cli.ts
  src/fetchServices.ts
Labels: cla: yes

#889 fix: assign ownership of repos to actools
  src/teams.json
Labels: cla: yes
