Repository googleapis/sloth, pull requests merged in 2021-04, with the labels that each got.

#907 chore: Fix python owlbot post processor image cloudbuild.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#915 feat: split workflows out to a new team
  src/teams.json
Labels: cla: yes

#913 feat: update repos.json and teams.json to include anthos-samples
  src/repos.json
  src/teams.json
Labels: cla: yes, samples

#918 build: add generated-files bot config
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
