Repository googleapis/sloth, pull requests merged in 2022-05, with the labels that each got.

#1062 chore: update teams.json to include new connector
  src/teams.json
Labels: size: xs

#1063 feat: add analytics-data and analytics-admin teams
  src/teams.json
Labels: size: xs

#1068 chore: adding additional api-labels for infra-databases team
  src/teams.json
Labels: size: xs

#1070 meta: move retail to ai team
  src/teams.json
Labels: size: xs

#1071 meta: add additional core/automation repos
  src/teams.json
Labels: size: s

#1074 build!: update library to use Node 12
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  package-lock.json
  package.json
  samples/package.json
  src/issue.ts
Labels: size: xl

#1077 chore: add cloud-sql-go-connector to repo.json
  src/repos.json
Labels: size: xs

#1079 chore: update repo metadata
  .github/CODEOWNERS
  .repo-metadata.json
Labels: size: xs

#1080 build: track additional node/automation repos
  src/repos.json
  src/teams.json
Labels: size: s

#1085 fix: allow higher QPS for getServiceConfig
  src/fetchServices.ts
Labels: size: xs

#1089 fix: preserve field names in the first row
  src/exportToSheets.ts
  src/fetchServices.ts
  test/test.exportToSheets.ts
Labels: size: s

#1084 chore: add blunderbuss.yml
  .github/blunderbuss.yml
Labels: automerge, size: xs

#1083 chore: add cloudbuild.yaml
  cloudbuild.yaml
Labels: size: m

#1092 fix: delete only excess data
  src/exportToSheets.ts
  src/fetchServices.ts
  src/util.ts
  test/test.exportToSheets.ts
Labels: size: s

#1095 chore: update deps
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  package-lock.json
  package.json
Labels: size: xl

#1097 fix: limit the delete range
  src/exportToSheets.ts
  src/fetchServices.ts
  src/util.ts
  test/test.exportToSheets.ts
Labels: size: s
